export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const SET_CURRENT_SONG_ID = "SET_CURRENT_SONG_ID";

export const PLAY_AUDIO = "PLAY_AUDIO";

export const PAUSE_AUDIO = "PAUSE_AUDIO";

export const SET_CURRENT_TIME = "SET_CURRENT_TIME";

export const SET_PROGRESS_PERCENT = "SET_PROGRESS_PERCENT";

export const SET_CURRENT_INDEX = "SET_CURRENT_INDEX";

export const SET_DURATION = "SET_DURATION";

export const SET_REPEAT = "SET_REPEAT";

export const TOGGLE_RANDOM = "TOGGLE_RANDOM";

export const SET_VOLUME = "SET_VOLUME";

export const SET_LIST_PLAYING = "SET_LIST_PLAYING";

export const SET_SONGS = "SET_SONGS";

export const SET_SONG_DETAIL = "SET_SONG_DETAIL";

export const SET_AREAS = "SET_AREAS";

export const SET_SONG_CATEGORY = "SET_SONG_CATEGORY";

export const SET_PLAYLIST_AREA = "SET_PLAYLIST_AREA";

export const SET_PLAYLIST_USER = "SET_PLAYLIST_USER";

export const SET_ARTIST_AREA = "SET_ARTIST_AREA";

export const SET_SEARCH_SUGGEST = "SET_SEARCH_SUGGEST";

export const SET_SEARCH_RESULT = "SET_SEARCH_RESULT";

export const SET_LIKED_SONG = "SET_LIKED_SONG";
